### ISSUE TITLE
Error: Disconnected walk for person '[id of person]'

### ISSUE THREAD

**Issue by 1BlattPapier** [eclipse-sumo/sumo#15600]
Filtering the generated trips using duarouter still retains trips like the following that cause a simulation to fail with the following error:
"Error: Disconnected walk for person '[id of person]'"

This is probably due to incorrectly imported junctions or walkingAreas from OSM. However, due to the large size of the network it is not feasible for me to fix all the issues and I prefer to filter the trips. It seems there is some issue in either duarouter or the simulation run.

[Link to the example on Google Drive due to the large network size.](https://drive.google.com/drive/folders/1EkwEd9kZPqsMEDwt3DO_gQd9k60tlAwx?usp=sharing)

Probably related to [this issue](https://github.com/eclipse-sumo/sumo/issues/12744#issue-1607602730).

**SUMO-version:** 1.20.0

**operating system:** macOS Sequoia 15.0.1

**Comment by namdre** [comment]
Please check whether it works with the latest release (version 1.21.0)

**Comment by 1BlattPapier** [comment]
Unfortunately the latest release does not show up when using brew. I also tried uninstalling, untapping and tapping the repository. Trying to build the tag v1_21_0 manually according to [the build instructions](https://sumo.dlr.de/docs/Installing/MacOS_Build.html) throws errors like the following:
```
[...]

Undefined symbols for architecture arm64:
  "void fmt::v11::detail::vformat_to<char>(fmt::v11::detail::buffer<char>&, fmt::v11::basic_string_view<char>, fmt::v11::detail::vformat_args<char>::type, fmt::v11::detail::locale_ref)", referenced from:
      void fmt::v11::print<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, double const&, long>(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, fmt::v11::basic_format_string<char, fmt::v11::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::type, fmt::v11::type_identity<double const&>::type, fmt::v11::type_identity<long>::type>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&, double const&, long&&) in libutils_vehicle.a[8](SUMOVTypeParameter.cpp.o)
ld: symbol(s) not found for architecture arm64
c++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [/Users/simon/Development/traffic-simulacra-generative-agents/sumo/bin/emissionsMap] Error 1
make[1]: *** [src/tools/CMakeFiles/emissionsMap.dir/all] Error 2
make[1]: *** Waiting for unfinished jobs....

[...]

Undefined symbols for architecture arm64:
  "void fmt::v11::detail::vformat_to<char>(fmt::v11::detail::buffer<char>&, fmt::v11::basic_string_view<char>, fmt::v11::detail::vformat_args<char>::type, fmt::v11::detail::locale_ref)", referenced from:
      void fmt::v11::print<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, double const&, long>(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, fmt::v11::basic_format_string<char, fmt::v11::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::type, fmt::v11::type_identity<double const&>::type, fmt::v11::type_identity<long>::type>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&, double const&, long&&) in libutils_vehicle.a[6](SUMOVehicleParameter.cpp.o)
ld: symbol(s) not found for architecture arm64
c++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [/Users/simon/Development/traffic-simulacra-generative-agents/sumo/bin/emissionsDrivingCycle] Error 1
make[1]: *** [src/tools/CMakeFiles/emissionsDrivingCycle.dir/all] Error 2

[...]

Undefined symbols for architecture arm64:
  "void fmt::v11::detail::vformat_to<char>(fmt::v11::detail::buffer<char>&, fmt::v11::basic_string_view<char>, fmt::v11::detail::vformat_args<char>::type, fmt::v11::detail::locale_ref)", referenced from:
      void fmt::v11::print<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>, double const&, long>(std::__1::basic_ostream<char, std::__1::char_traits<char>>&, fmt::v11::basic_format_string<char, fmt::v11::type_identity<std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>>::type, fmt::v11::type_identity<double const&>::type, fmt::v11::type_identity<long>::type>, std::__1::basic_string<char, std::__1::char_traits<char>, std::__1::allocator<char>>&&, double const&, long&&) in libutils_shapes.a[2](PointOfInterest.cpp.o)
ld: symbol(s) not found for architecture arm64
c++: error: linker command failed with exit code 1 (use -v to see invocation)
make[2]: *** [/Users/simon/Development/traffic-simulacra-generative-agents/sumo/bin/polyconvert] Error 1
make[1]: *** [src/polyconvert/CMakeFiles/polyconvert.dir/all] Error 2

[...]

[ 66%] Built target libtracicpp
make: *** [all] Error 2
```
