### ISSUE TITLE
Sumo 1.24 is failing to build with GDAL 3.12

### ISSUE THREAD

**Issue by imincik** [eclipse-sumo/sumo#17443]
Sumo 1.24.0 is failing to build with GDAL 3.12

```
[ 43%] Building CXX object src/netbuild/CMakeFiles/netbuild.dir/NBDistrictCont.cpp.o
/build/source/src/netimport/NIImporter_ArcView.cpp: In member function 'void NIImporter_ArcView::load()':
/build/source/src/netimport/NIImporter_ArcView.cpp:146:61: error: invalid conversion from 'const OGRSpatialReference*' to 'OGRSpatialReference*' [-fpermissive]
  146 |     OGRSpatialReference* origTransf = poLayer->GetSpatialRef();
      |                                       ~~~~~~~~~~~~~~~~~~~~~~^~
      |                                                             |
      |                                                             const OGRSpatialReference*


...


[ 46%] Building CXX object src/router/CMakeFiles/router.dir/RONetHandler.cpp.o
/build/source/src/netbuild/NBHeightMapper.cpp: In member function 'int NBHeightMapper::loadShapeFile(const std::string&)':
/build/source/src/netbuild/NBHeightMapper.cpp:199:55: error: invalid conversion from 'const OGRSpatialReference*' to 'OGRSpatialReference*' [-fpermissive]
  199 |     OGRSpatialReference* sr_src = layer->GetSpatialRef();
      |                                   ~~~~~~~~~~~~~~~~~~~~^~
      |                                                       |
      |                                                       const OGRSpatialReference*

```

**Comment by imincik** [comment]
Version 1.25.0 is building fine. I am closing this issue.
